name: CI                            
on:
branch
  pull_request:
    branches: [ main ]    
jobs:	               
  build:             
    runs-on: ubuntu-latest
    steps:                		
      - uses: actions/checkout@v2
      
      - name: npm install        
        run: npm i		

      - name: Deploy to gh-pages
        run: |         
   		git remote set-url origin https://git:${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
           npm run deploy
