name: CI                           
on:
  pull_request:
    branches: [ main ]  
jobs:	             
  build:            
    runs-on: ubuntu-latest
    steps:                		
      - uses: actions/checkout@v2
      
      - name: npm install       
        run: npm i		

      - name: Deploy to gh-pages
        run: |      
   		git remote set-url origin https://git:${{ secrets.GH_ACCESS_TOKEN }}@github.com/${lgnvk/UI_Storybook}.git
      npm run deploy
